vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        game_images:
            uri_prefix: /images/game
            upload_destination: '%kernel.project_dir%/public/images/game'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer